# Deployment to Render.com
services:
  - type: web
    name: token-price-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      # Add your environment variables here:
      # - key: MONGODB_URI
      #   value: your_mongodb_connection_string
      # - key: ALCHEMY_API_KEY  
      #   value: your_alchemy_api_key
